# Generated by Django 4.2.7 on 2025-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0002_userprofile_deliverybooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverybooking',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliverybooking',
            name='whatsapp_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
