# Generated by Django 4.2.7 on 2025-10-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_remove_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='age_group',
            field=models.CharField(choices=[('under_18', 'Under 18'), ('18_25', '18-25'), ('26_35', '26-35'), ('36_45', '36-45'), ('46_55', '46-55'), ('56_65', '56-65'), ('over_65', 'Over 65')], default='18_25', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('inquiry', 'General Inquiry'), ('suggestion', 'Suggestion'), ('feedback', 'Feedback'), ('other', 'Other')], default='inquiry', max_length=20),
        ),
    ]
