# Generated by Django 4.2.7 on 2025-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_contactmessage_age_group_contactmessage_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybooking',
            name='cancellation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverybooking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('customer_request', 'Customer Request'), ('out_of_stock', 'Out of Stock'), ('delivery_area', 'Outside Delivery Area'), ('payment_issue', 'Payment Issue'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='deliverybooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
