# Generated by Django 4.2.7 on 2025-10-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_deliverybooking_cancellation_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverybooking',
            name='delivery_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
