# Generated by Django 4.2.7 on 2026-09-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0008_stockentry_protect_sold_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
